### ISSUE TITLE
Firebase CLI native support

### ISSUE THREAD

**Issue by jthegedus** [rioam2/firebase-project-manager#15]
Just an FYI since I have also been looking into a tool for this https://github.com/firebase/firebase-tools/releases/tag/v7.2.3

**Comment by rioam2** [comment]
Good eye, James. I’ll keep an eye there to see how the APIs mature. In the meantime, this tool should fill my need to automate deployments.. 

If you do experiment with the native apis, let me know how easy they are to use!

**Comment by jthegedus** [comment]
Will do, am keen to test this out too 🎉
